/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {
//    PUBLIC BOOLEAN SOMELIBRARYMETHOD() {
//        RETURN TRUE;
//    }
	public static void main(String[] args) {
		// TODO Auto-generated method stub
		System.out.println("서버실행");
	}

	public boolean someLibraryMethod() {
		// TODO Auto-generated method stub
		System.out.println("someLibraryMethod 실행");
		return false;
	}
}
